### ISSUE TITLE
Panic in EqualsByID

### ISSUE THREAD

**Issue by aanm** [cilium/hubble#197]
```
2020-03-23T11:24:17.76680844Z time="2020-03-23T11:24:17Z" level=warning msg="failed to resolve identity" error="[GET /identity/{id}][404] getIdentityIdNotFound " identity=301132
2020-03-23T11:24:17.767033607Z time="2020-03-23T11:24:17Z" level=warning msg="failed to resolve identity" error="[GET /identity/{id}][404] getIdentityIdNotFound " identity=301132
2020-03-23T11:24:17.767431978Z time="2020-03-23T11:24:17Z" level=warning msg="failed to resolve identity" error="[GET /identity/{id}][404] getIdentityIdNotFound " identity=300031
2020-03-23T11:24:17.767621102Z time="2020-03-23T11:24:17Z" level=warning msg="failed to resolve identity" error="[GET /identity/{id}][404] getIdentityIdNotFound " identity=301132
2020-03-23T11:24:17.767835101Z time="2020-03-23T11:24:17Z" level=warning msg="failed to resolve identity" error="[GET /identity/{id}][404] getIdentityIdNotFound " identity=301132
2020-03-23T11:24:17.864479667Z panic: runtime error: invalid memory address or nil pointer dereference
2020-03-23T11:24:17.864517105Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xc7443f]
2020-03-23T11:24:17.864521141Z 
2020-03-23T11:24:17.864524132Z goroutine 71 [running]:
2020-03-23T11:24:17.864527019Z github.com/cilium/hubble/pkg/api/v1.(*Endpoint).EqualsByID(...)
2020-03-23T11:24:17.864530071Z 	/go/src/github.com/cilium/hubble/pkg/api/v1/endpoint.go:35
2020-03-23T11:24:17.864533173Z github.com/cilium/hubble/pkg/api/v1.(*Endpoints).SyncEndpoints(0xc0003e2ba0, 0xc008d17f00, 0xe, 0x10)
2020-03-23T11:24:17.864536407Z 	/go/src/github.com/cilium/hubble/pkg/api/v1/endpoint.go:80 +0xdf
2020-03-23T11:24:17.864539452Z github.com/cilium/hubble/pkg/cilium.(*State).syncEndpoints(0xc0002041e0)
2020-03-23T11:24:17.864542278Z 	/go/src/github.com/cilium/hubble/pkg/cilium/endpoint.go:67 +0x786
2020-03-23T11:24:17.864545314Z created by github.com/cilium/hubble/pkg/cilium.(*State).Start
2020-03-23T11:24:17.864560806Z 	/go/src/github.com/cilium/hubble/pkg/cilium/state.go:79 +0x43
```

**Comment by glibsm** [comment]
Fixed in `0.5.1`
